spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.111.131:1433;databaseName=weight20
    username: xxxx
    password: xxxxxxxxx
calcifer:
  weight:
    slave-ip: 10.206.4.243
    scale-port: COM3
    front-card-reader-port: COM2
    back-card-reader-port: COM4
    enable-auth: true
    enable-auto-scan: true
    enable-modbus-device-init: true
    enable-serial-device-init: true
    sampled-time: 10
    min-weight: 1000
    max-weight: 100000
    # 等待时间，单位毫秒，超过该时间没有状态变化将重置系统
    wait-time: 60000

logging:
  config: file:config/logback-spring.xml