spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.111.131:1433;databaseName=gcgl;
    username: SA
    password: xwsssyea1009.
    hikari:
      connection-test-query: SELECT 1
weight:
  slave-ip: 10.206.4.243
  coil-num: 6
  enable-auth: false
  enable-auto-scan: false
  enable-modbus-device-init: false
  enable-serial-device-init: false
  enable-voice: false
  plate-reader-address: 192.168.1.100, 192.168.1.100
  # 控制modbus设备的时间间隔
  modbus-control-sleep-time: 100
  # 称重时的采样次数
  sampled-time: 10
  min-weight: 1000
  max-weight: 100000
  # 等待时间，单位毫秒，超过该时间没有状态变化将重置系统
  wait-time: 60000
  # 红外确认阈值（单位：次数，配合fixedDelay=500ms使用，4次代表2秒）
  infrared-confirm-threshold: 4
  modbus-device-info-path: classpath:config/modbus_device_info.json
  serial-device-info-path: classpath:config/serial_device_info.json
  standard-template: classpath:config/report.jasper
  delivery-template: classpath:config/report2.jasper
  waste-template: classpath:config/report_waste.jasper
  raw-template: classpath:config/report_raw.jasper
  index-menu: classpath:config/index_menu.json

  active-scale: ToledoT800
  scales:
    ToledoT800:
      frame-length: 18
      terminator: "0D0A"
      weight-start: 16
      weight-end: 28
      status-start: 0
      status-end: 4
      stable-value: "5354"
    KeliD2008:
      frame-length: 12
      terminator: "03"
      weight-start: 4
      weight-end: 16
      status-start: 18
      status-end: 20
      stable-value: "01"

logging:
  config: classpath:config/logback-spring.xml
