spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.111.131:1433;databaseName=weight20
    username: xxxx
    password: xxxxxxxxx
calcifer:
  weight:
    slave-ip: 10.206.4.243
    scale-port: COM3
    front-card-reader-port: COM2
    back-card-reader-port: COM4
    enable-auth: true
    enable-auto-scan: true
    enable-device-init: true
    active-scale: ToledoT800
    scales:
      ToledoT800:
        frame-length: 18
        terminator: "0D0A"
        weight-start: 16
        weight-end: 28
        status-start: 0
        status-end: 4
        stable-value: "5354"
      KeliD2008:
        frame-length: 12
        terminator: "03"
        weight-start: 4
        weight-end: 16
        status-start: 18
        status-end: 20
        stable-value: "01"

logging:
  config: file:config/logback-spring.xml